// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bouwmarkt_API.Data;

#nullable disable

namespace bouwmarktAPI.Migrations
{
    [DbContext(typeof(BouwmarktContext))]
    partial class BouwmarktContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bouwmarkt_API.Models.Koopzondag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EindTijd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vestigingsnummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vestigingsnummer");

                    b.ToTable("Koopzondagen");
                });

            modelBuilder.Entity("bouwmarkt_API.Models.Vestiging", b =>
                {
                    b.Property<int>("Vestigingsnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vestigingsnummer"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Telefoonnumer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VestigingsNaam")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Vestigingsnummer");

                    b.ToTable("Vestigingen");
                });

            modelBuilder.Entity("bouwmarkt_API.Models.Koopzondag", b =>
                {
                    b.HasOne("bouwmarkt_API.Models.Vestiging", "Vestiging")
                        .WithMany("Koopzondagen")
                        .HasForeignKey("Vestigingsnummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vestiging");
                });

            modelBuilder.Entity("bouwmarkt_API.Models.Vestiging", b =>
                {
                    b.Navigation("Koopzondagen");
                });
#pragma warning restore 612, 618
        }
    }
}
